uploadPath: notyet
imgPath: notyet

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${s3_access_key}
      secret-key: ${s3_secret_key}
    s3:
      bucket: ${s3_bucket}
