cloud:
  aws:
    region:
      static: ${s3_region}
    stack:
      auto: false
    credentials:
      access-key: ${s3_access_key}
      secret-key: ${s3_secret_key}
    s3:
      bucket: ${s3_bucket}
