spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db_url:jdbc:mysql://localhost:3306/legacy_board}
    username: ${db_username:root}
    password: ${db_password:1234}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: ${db_ddl:update} # validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  web.resources.add-mappings: false # https://www.leeby.one/posts/spring.web.resources.add-mappings-%EC%98%B5%EC%85%98/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    encoding:
      charset: utf-8
    context-path: /
  port: 8080

---

spring:
  profiles:
    active: ${profile:local}