spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: ${db.ddl:create-drop}
    show-sql: false

  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true

  web.resources.add-mappings: false # https://www.leeby.one/posts/spring.web.resources.add-mappings-%EC%98%B5%EC%85%98/

server:
  servlet:
    encoding:
      charset: utf-8
    context-path: /
  port: 8080


