spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: ${db.ddl:create-drop}
    show-sql: false

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true

server:
  servlet:
    encoding:
      charset: utf-8
    context-path: /
  port: 8080