alter table board drop foreign key FKsds8ox89wwf6aihinar49rmfy;
alter table board_tag drop foreign key FKn9tsgp9bc6132ojkja6r20i8;
alter table board_tag drop foreign key FK4gcg6nlkb1p1ov5neg0u4iy6g;
alter table reply drop foreign key FKcs9hiip0bv9xxfrgoj0lwv2dt;
alter table reply drop foreign key FKen6vrmi5oth4bg6ybfc202fmu;
drop table if exists board;
drop table if exists board_tag;
drop table if exists member;
drop table if exists reply;
drop table if exists tag;
create table board (id bigint not null auto_increment, created_at datetime(6), modified_at datetime(6), content TEXT not null, count integer not null, title varchar(255) not null, topic varchar(255) not null, member_id bigint, primary key (id)) engine=InnoDB;
create table board_tag (id bigint not null auto_increment, created_at datetime(6), modified_at datetime(6), board_id bigint, tag_id bigint, primary key (id)) engine=InnoDB;
create table member (id bigint not null auto_increment, created_at datetime(6), modified_at datetime(6), email varchar(255) not null, nickname varchar(255) not null, password varchar(255) not null, role varchar(255) not null, primary key (id)) engine=InnoDB;
create table reply (id bigint not null auto_increment, created_at datetime(6), modified_at datetime(6), content TEXT not null, board_id bigint, member_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, created_at datetime(6), modified_at datetime(6), name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table member add constraint UK_mbmcqelty0fbrvxp1q58dn57t unique (email);
alter table member add constraint UK_hh9kg6jti4n1eoiertn2k6qsc unique (nickname);
alter table tag add constraint UK_1wdpsed5kna2y38hnbgrnhi5b unique (name);
alter table board add constraint FKsds8ox89wwf6aihinar49rmfy foreign key (member_id) references member (id);
alter table board_tag add constraint FKn9tsgp9bc6132ojkja6r20i8 foreign key (board_id) references board (id);
alter table board_tag add constraint FK4gcg6nlkb1p1ov5neg0u4iy6g foreign key (tag_id) references tag (id);
alter table reply add constraint FKcs9hiip0bv9xxfrgoj0lwv2dt foreign key (board_id) references board (id);
alter table reply add constraint FKen6vrmi5oth4bg6ybfc202fmu foreign key (member_id) references member (id);