drop table if exists board cascade
drop table if exists board_img cascade
drop table if exists member cascade
drop table if exists reply cascade
create table board (id bigint generated by default as identity, created_at timestamp(6), modified_at timestamp(6), content TEXT not null, count integer not null, title varchar(255) not null, member_id bigint, primary key (id))
create table board_img (board_id bigint not null, images varchar(255))
create table member (id bigint generated by default as identity, created_at timestamp(6), modified_at timestamp(6), email varchar(255) not null, nickname varchar(255) not null, password varchar(255) not null, role varchar(255) not null, primary key (id))
create table reply (id bigint generated by default as identity, created_at timestamp(6), modified_at timestamp(6), content TEXT not null, board_id bigint, member_id bigint, primary key (id))
alter table if exists member add constraint UK_member_email unique (email)
alter table if exists member add constraint UK_member_nickname unique (nickname)
alter table if exists board add constraint FKsds8ox89wwf6aihinar49rmfy foreign key (member_id) references member
alter table if exists board_img add constraint FKey99sxtgmf5fpa0dfs2r2hxaa foreign key (board_id) references board
alter table if exists reply add constraint FKcs9hiip0bv9xxfrgoj0lwv2dt foreign key (board_id) references board
alter table if exists reply add constraint FKen6vrmi5oth4bg6ybfc202fmu foreign key (member_id) references member
